Server:
  Port: 8901
  ReadTimeout: 15s
  WriteTimeout: 15s

API:
  BasePath: ""
  APITimeout: 15s
  EnableSwagger: true

Database:
  SlaveDSN: "postgres://postgres:1235813@localhost:5432/ums-votechain?sslmode=disable"
  MasterDSN: "postgres://postgres:1235813@localhost:5432/ums-votechain?sslmode=disable"
  RetryInterval: 10
  MaxIdleConn: 10
  MaxConn: 10
  ConnMaxLifetime: 10s

Kafka:
  Producer:
    Brokers:
      - localhost:9092
    MaxAttempt: 5
    Idempotent: true
  Topics:
    MasterDataUser:
      Value: ""
      ErrorHandler: "Phase1"
      WithBackOff: true


BlockchainConfig:
  GanacheURL: "http://localhost:7545"
  ContractAddress: "0x497686BEdEe721E53C1d55B321Ee720788DB4Daa"

JWT:
  Secret: "^87adb2&91hnGaWd7"

Encryption:
  Key : "NZkrqmVGg6Bi4QbqGXbH9wz3Q0+NCGvMKA2j8hqD5eM="